// data.js — Bleach Guessr
// n=nom | r=race | sx=sexe | arc=arc d'introduction | af=affiliation | d=dangerosité (1-5)

const CHARS = [
  // ── KARAKURA / PROTAGONISTES ─────────────────────────────────────────────
  {n:"Ichigo Kurosaki",             r:"Humain",    sx:"M", arc:"Agent of Shinigami",       af:"Karakura",             d:5},
  {n:"Orihime Inoue",               r:"Humain",    sx:"F", arc:"Agent of Shinigami",       af:"Karakura",             d:2},
  {n:"Yasutora Sado",               r:"Humain",    sx:"M", arc:"Agent of Shinigami",       af:"Karakura",             d:3},
  {n:"Uryuu Ishida",                r:"Quincy",    sx:"M", arc:"Agent of Shinigami",       af:"Karakura",             d:4},
  {n:"Kisuke Urahara",              r:"Shinigami", sx:"M", arc:"Agent of Shinigami",       af:"Indépendant",          d:5},
  {n:"Yoruichi Shihoin",            r:"Shinigami", sx:"F", arc:"Agent of Shinigami",       af:"Indépendant",          d:5},
  {n:"Isshin Kurosaki",             r:"Shinigami", sx:"M", arc:"Agent of Shinigami",       af:"Karakura",             d:5},
  {n:"Kon",                         r:"Mod-Soul",  sx:"M", arc:"Agent of Shinigami",       af:"Karakura",             d:1},
  {n:"Tessai Tsukabishi",           r:"Shinigami", sx:"M", arc:"Agent of Shinigami",       af:"Indépendant",          d:4},
  {n:"Jinta Hanakari",              r:"Humain",    sx:"M", arc:"Agent of Shinigami",       af:"Indépendant",          d:1},
  {n:"Ururu Tsumugiya",             r:"Humain",    sx:"F", arc:"Agent of Shinigami",       af:"Indépendant",          d:2},

  // ── GOTEI 13 — CAPITAINES ────────────────────────────────────────────────
  {n:"Rukia Kuchiki",               r:"Shinigami", sx:"F", arc:"Agent of Shinigami",       af:"Gotei 13",             d:4},
  {n:"Renji Abarai",                r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:4},
  {n:"Genryusai Yamamoto",          r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:5},
  {n:"Soi Fon",                     r:"Shinigami", sx:"F", arc:"Soul Society",             af:"Gotei 13",             d:4},
  {n:"Gin Ichimaru",                r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:5},
  {n:"Retsu Unohana",               r:"Shinigami", sx:"F", arc:"Soul Society",             af:"Gotei 13",             d:5},
  {n:"Sosuke Aizen",                r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:5},
  {n:"Byakuya Kuchiki",             r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:5},
  {n:"Sajin Komamura",              r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:4},
  {n:"Shunsui Kyoraku",             r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:5},
  {n:"Kaname Tousen",               r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:4},
  {n:"Toshiro Hitsugaya",           r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:5},
  {n:"Kenpachi Zaraki",             r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:5},
  {n:"Mayuri Kurotsuchi",           r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:4},
  {n:"Jushiro Ukitake",             r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:4},

  // ── GOTEI 13 — LIEUTENANTS & OFFICIERS ──────────────────────────────────
  {n:"Chojiro Sasakibe",            r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:3},
  {n:"Marenoshin Omaeda",           r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:2},
  {n:"Momo Hinamori",               r:"Shinigami", sx:"F", arc:"Soul Society",             af:"Gotei 13",             d:3},
  {n:"Rangiku Matsumoto",           r:"Shinigami", sx:"F", arc:"Soul Society",             af:"Gotei 13",             d:3},
  {n:"Yachiru Kusajishi",           r:"Shinigami", sx:"F", arc:"Soul Society",             af:"Gotei 13",             d:4},
  {n:"Nemu Kurotsuchi",             r:"Mod-Soul",  sx:"F", arc:"Soul Society",             af:"Gotei 13",             d:3},
  {n:"Nanao Ise",                   r:"Shinigami", sx:"F", arc:"Soul Society",             af:"Gotei 13",             d:3},
  {n:"Isane Kotetsu",               r:"Shinigami", sx:"F", arc:"Soul Society",             af:"Gotei 13",             d:3},
  {n:"Izuru Kira",                  r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:3},
  {n:"Shuhei Hisagi",               r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:3},
  {n:"Ikkaku Madarame",             r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:3},
  {n:"Yumichika Ayasegawa",         r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:3},
  {n:"Hanataro Yamada",             r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:1},
  {n:"Ganju Shiba",                 r:"Humain",    sx:"M", arc:"Soul Society",             af:"Indépendant",          d:2},
  {n:"Kukaku Shiba",                r:"Humain",    sx:"F", arc:"Soul Society",             af:"Indépendant",          d:3},
  {n:"Ginrei Kuchiki",              r:"Shinigami", sx:"M", arc:"Soul Society",             af:"Gotei 13",             d:4},

  // ── VIZARD ───────────────────────────────────────────────────────────────
  {n:"Shinji Hirako",               r:"Vizard",    sx:"M", arc:"Arrancar",                 af:"Gotei 13",             d:4},
  {n:"Hiyori Sarugaki",             r:"Vizard",    sx:"F", arc:"Arrancar",                 af:"Indépendant",          d:3},
  {n:"Lisa Yadomaru",               r:"Vizard",    sx:"F", arc:"Fake Karakura",            af:"Gotei 13",             d:4},
  {n:"Love Aikawa",                 r:"Vizard",    sx:"M", arc:"Fake Karakura",            af:"Gotei 13",             d:4},
  {n:"Kensei Muguruma",             r:"Vizard",    sx:"M", arc:"Fake Karakura",            af:"Gotei 13",             d:4},
  {n:"Rose Otoribashi",             r:"Vizard",    sx:"M", arc:"Fake Karakura",            af:"Gotei 13",             d:4},
  {n:"Mashiro Kuna",                r:"Vizard",    sx:"F", arc:"Fake Karakura",            af:"Indépendant",          d:3},
  {n:"Hachigen Ushoda",             r:"Vizard",    sx:"M", arc:"Fake Karakura",            af:"Indépendant",          d:4},

  // ── ESPADA ───────────────────────────────────────────────────────────────
  {n:"Coyote Starrk",               r:"Arrancar",  sx:"M", arc:"Arrancar",                 af:"Espada",               d:5},
  {n:"Baraggan Louisenbairn",        r:"Arrancar",  sx:"M", arc:"Fake Karakura",            af:"Espada",               d:5},
  {n:"Tier Harribel",               r:"Arrancar",  sx:"F", arc:"Fake Karakura",            af:"Espada",               d:5},
  {n:"Ulquiorra Cifer",             r:"Arrancar",  sx:"M", arc:"Arrancar",                 af:"Espada",               d:5},
  {n:"Nnoitra Gilga",               r:"Arrancar",  sx:"M", arc:"Hueco Mundo",              af:"Espada",               d:5},
  {n:"Grimmjow Jaegerjaquez",       r:"Arrancar",  sx:"M", arc:"Arrancar",                 af:"Espada",               d:5},
  {n:"Zommari Rureaux",             r:"Arrancar",  sx:"M", arc:"Hueco Mundo",              af:"Espada",               d:4},
  {n:"Szayelaporro Grantz",         r:"Arrancar",  sx:"M", arc:"Hueco Mundo",              af:"Espada",               d:4},
  {n:"Aaroniero Arruruerie",        r:"Arrancar",  sx:"M", arc:"Hueco Mundo",              af:"Espada",               d:4},
  {n:"Yammy Llargo",                r:"Arrancar",  sx:"M", arc:"Arrancar",                 af:"Espada",               d:5},
  {n:"Nelliel Tu Odelschwanck",     r:"Arrancar",  sx:"F", arc:"Hueco Mundo",              af:"Hueco Mundo",          d:5},
  {n:"Luppi Antenor",               r:"Arrancar",  sx:"M", arc:"Arrancar",                 af:"Espada",               d:3},
  {n:"Wonderweiss Margela",         r:"Arrancar",  sx:"M", arc:"Fake Karakura",            af:"Espada",               d:4},
  {n:"Franceska Mila Rose",         r:"Arrancar",  sx:"F", arc:"Arrancar",                 af:"Espada",               d:3},
  {n:"Apache",                      r:"Arrancar",  sx:"F", arc:"Arrancar",                 af:"Espada",               d:3},
  {n:"Sun-Sun",                     r:"Arrancar",  sx:"F", arc:"Arrancar",                 af:"Espada",               d:3},
  {n:"Loly Aivirrne",               r:"Arrancar",  sx:"F", arc:"Arrancar",                 af:"Espada",               d:2},
  {n:"Menoly Mallia",               r:"Arrancar",  sx:"F", arc:"Arrancar",                 af:"Espada",               d:2},
  {n:"Dordoni Alessandro",          r:"Arrancar",  sx:"M", arc:"Hueco Mundo",              af:"Hueco Mundo",          d:3},
  {n:"Cirucci Sanderwicci",         r:"Arrancar",  sx:"F", arc:"Hueco Mundo",              af:"Hueco Mundo",          d:3},
  {n:"Gantenbainne Mosqueda",       r:"Arrancar",  sx:"M", arc:"Hueco Mundo",              af:"Hueco Mundo",          d:3},
  {n:"Findorr Calius",              r:"Arrancar",  sx:"M", arc:"Fake Karakura",            af:"Espada",               d:3},
  {n:"Charlotte Cuuhlhourne",       r:"Arrancar",  sx:"M", arc:"Fake Karakura",            af:"Espada",               d:3},
  {n:"Shawlong Koufang",            r:"Arrancar",  sx:"M", arc:"Arrancar",                 af:"Espada",               d:3},
  {n:"Pesche Guatiche",             r:"Arrancar",  sx:"M", arc:"Hueco Mundo",              af:"Hueco Mundo",          d:2},
  {n:"Dondochakka Birstanne",       r:"Arrancar",  sx:"M", arc:"Hueco Mundo",              af:"Hueco Mundo",          d:2},
  {n:"Grand Fisher",                r:"Hollow",    sx:"M", arc:"Agent of Shinigami",       af:"Hueco Mundo",          d:3},

  // ── FULLBRING / XCUTION ──────────────────────────────────────────────────
  {n:"Kugo Ginjo",                  r:"Fullbring", sx:"M", arc:"Fullbring",                af:"Xcution",              d:4},
  {n:"Shukuro Tsukishima",          r:"Fullbring", sx:"M", arc:"Fullbring",                af:"Xcution",              d:4},
  {n:"Riruka Dokugamine",           r:"Fullbring", sx:"F", arc:"Fullbring",                af:"Xcution",              d:3},
  {n:"Yukio Hans Vorarlberna",      r:"Fullbring", sx:"M", arc:"Fullbring",                af:"Xcution",              d:3},
  {n:"Jackie Tristan",              r:"Fullbring", sx:"F", arc:"Fullbring",                af:"Xcution",              d:3},
  {n:"Giriko Kutsuzawa",            r:"Fullbring", sx:"M", arc:"Fullbring",                af:"Xcution",              d:3},
  {n:"Moe Shishigawara",            r:"Fullbring", sx:"M", arc:"Fullbring",                af:"Xcution",              d:2},

  // ── WANDENREICH ──────────────────────────────────────────────────────────
  {n:"Yhwach",                      r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:5},
  {n:"Jugram Haschwalth",           r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:5},
  {n:"As Nodt",                     r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:5},
  {n:"Lille Barro",                 r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:5},
  {n:"Gerard Valkyrie",             r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:5},
  {n:"Pernida Parnkgjas",           r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:5},
  {n:"Askin Nakk Le Vaar",          r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:5},
  {n:"Gremmy Thoumeaux",            r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:5},
  {n:"Bazz-B",                      r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:4},
  {n:"Cang Du",                     r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:4},
  {n:"BG9",                         r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:4},
  {n:"PePe Waccabrada",             r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:4},
  {n:"Liltotto Lamperd",            r:"Quincy",    sx:"F", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:4},
  {n:"Bambietta Basterbine",        r:"Quincy",    sx:"F", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:4},
  {n:"Candice Catnipp",             r:"Quincy",    sx:"F", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:4},
  {n:"Meninas McAllon",             r:"Quincy",    sx:"F", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:4},
  {n:"Giselle Gewelle",             r:"Quincy",    sx:"F", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:4},
  {n:"Mask De Masculine",           r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:4},
  {n:"Quilge Opie",                 r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:4},
  {n:"NaNaNa Najahkoop",            r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:3},
  {n:"Driscoll Berci",              r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:3},
  {n:"Royd Lloyd",                  r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:4},
  {n:"Nianzol Weizol",              r:"Quincy",    sx:"M", arc:"Thousand-Year Blood War",  af:"Wandenreich",          d:4},
];
